#! /bin/sh

set -e

case "$1" in
  configure)
        if [ ! -L /etc/freeradius/mods-enabled/dhcp ]; then
            (cd /etc/freeradius/mods-enabled/ && ln -fs ../mods-available/dhcp dhcp)
        fi

        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
          invoke-rc.d freeradius force-reload
        else
          /etc/init.d/freeradius force-reload
        fi
        ;;
  abort-upgrade)
        ;;
  abort-remove)
        ;;
  abort-deconfigure)
        ;;
esac

#DEBHELPER#

